package com.example.nutrition.domain.constants

import com.example.nutrition.domain.model.FoodTemplate

/**
 * 常见食物预设模板
 *
 * 数据来源：综合公开营养成分表（每 100g 可食部），供录入时快速选择。
 * 未来可通过网络抓取或远程 JSON 更新此列表。
 */
object PresetFoodTemplates {

    private val TEMPLATES = listOf(
        FoodTemplate(
            id = "preset-food-001",
            name = "米饭",
            calories = 116.0,
            protein = 2.6,
            fat = 0.3,
            carbs = 25.6,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-002",
            name = "馒头",
            calories = 223.0,
            protein = 7.0,
            fat = 1.1,
            carbs = 47.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-003",
            name = "面条（煮）",
            calories = 110.0,
            protein = 2.7,
            fat = 0.2,
            carbs = 22.8,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-004",
            name = "燕麦片",
            calories = 389.0,
            protein = 16.9,
            fat = 6.9,
            carbs = 66.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-005",
            name = "全麦面包",
            calories = 247.0,
            protein = 13.0,
            fat = 3.5,
            carbs = 41.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-006",
            name = "白面包",
            calories = 265.0,
            protein = 9.0,
            fat = 3.2,
            carbs = 49.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-007",
            name = "饺子",
            calories = 218.0,
            protein = 8.0,
            fat = 7.0,
            carbs = 30.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-008",
            name = "包子",
            calories = 218.0,
            protein = 7.0,
            fat = 5.0,
            carbs = 33.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-009",
            name = "馄饨",
            calories = 198.0,
            protein = 6.0,
            fat = 4.0,
            carbs = 32.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-010",
            name = "米粉",
            calories = 111.0,
            protein = 2.0,
            fat = 0.1,
            carbs = 25.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-011",
            name = "河粉",
            calories = 122.0,
            protein = 2.6,
            fat = 0.4,
            carbs = 27.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-012",
            name = "年糕",
            calories = 156.0,
            protein = 3.0,
            fat = 0.3,
            carbs = 34.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-013",
            name = "粽子（肉粽）",
            calories = 228.0,
            protein = 6.0,
            fat = 5.0,
            carbs = 38.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-014",
            name = "玉米",
            calories = 112.0,
            protein = 4.0,
            fat = 1.2,
            carbs = 22.8,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-015",
            name = "红薯",
            calories = 86.0,
            protein = 1.6,
            fat = 0.1,
            carbs = 20.1,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-016",
            name = "紫薯",
            calories = 106.0,
            protein = 1.6,
            fat = 0.2,
            carbs = 25.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-017",
            name = "土豆",
            calories = 77.0,
            protein = 2.0,
            fat = 0.1,
            carbs = 17.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-018",
            name = "山药",
            calories = 57.0,
            protein = 1.9,
            fat = 0.2,
            carbs = 12.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-019",
            name = "芋头",
            calories = 58.0,
            protein = 1.3,
            fat = 0.2,
            carbs = 12.8,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-020",
            name = "荞麦面",
            calories = 99.0,
            protein = 5.0,
            fat = 0.5,
            carbs = 20.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-021",
            name = "意大利面（煮）",
            calories = 158.0,
            protein = 5.8,
            fat = 0.9,
            carbs = 30.9,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-022",
            name = "藜麦",
            calories = 120.0,
            protein = 4.4,
            fat = 1.9,
            carbs = 21.3,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-023",
            name = "紫米",
            calories = 356.0,
            protein = 8.0,
            fat = 1.6,
            carbs = 75.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-024",
            name = "黑米",
            calories = 341.0,
            protein = 9.0,
            fat = 2.5,
            carbs = 72.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-025",
            name = "小米",
            calories = 361.0,
            protein = 9.0,
            fat = 3.1,
            carbs = 73.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-026",
            name = "糙米",
            calories = 362.0,
            protein = 7.9,
            fat = 2.7,
            carbs = 76.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-027",
            name = "糯米",
            calories = 348.0,
            protein = 7.3,
            fat = 1.0,
            carbs = 77.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-028",
            name = "麦片",
            calories = 333.0,
            protein = 11.0,
            fat = 2.5,
            carbs = 70.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-029",
            name = "饼干",
            calories = 502.0,
            protein = 7.0,
            fat = 24.0,
            carbs = 67.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-030",
            name = "油条",
            calories = 388.0,
            protein = 6.5,
            fat = 20.0,
            carbs = 45.0,
            micronutrients = emptyList(),
            tags = listOf("主食", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-031",
            name = "煎饼",
            calories = 289.0,
            protein = 7.0,
            fat = 8.0,
            carbs = 45.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-032",
            name = "蛋糕",
            calories = 371.0,
            protein = 6.0,
            fat = 15.0,
            carbs = 53.0,
            micronutrients = emptyList(),
            tags = listOf("主食", "蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-033",
            name = "蛋挞",
            calories = 329.0,
            protein = 7.0,
            fat = 21.0,
            carbs = 30.0,
            micronutrients = emptyList(),
            tags = listOf("主食", "蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-034",
            name = "月饼",
            calories = 410.0,
            protein = 6.0,
            fat = 18.0,
            carbs = 58.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-035",
            name = "汤圆",
            calories = 280.0,
            protein = 4.0,
            fat = 10.0,
            carbs = 45.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-036",
            name = "手抓饼",
            calories = 306.0,
            protein = 6.0,
            fat = 18.0,
            carbs = 35.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-037",
            name = "粉丝",
            calories = 350.0,
            protein = 0.8,
            fat = 0.3,
            carbs = 86.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-038",
            name = "凉皮",
            calories = 117.0,
            protein = 2.5,
            fat = 0.6,
            carbs = 25.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-039",
            name = "烧麦",
            calories = 220.0,
            protein = 7.0,
            fat = 6.0,
            carbs = 34.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-040",
            name = "春卷",
            calories = 275.0,
            protein = 5.0,
            fat = 13.0,
            carbs = 33.0,
            micronutrients = emptyList(),
            tags = listOf("主食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-041",
            name = "蛋炒饭",
            calories = 188.0,
            protein = 6.0,
            fat = 7.0,
            carbs = 27.0,
            micronutrients = emptyList(),
            tags = listOf("主食", "蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-042",
            name = "鸡蛋",
            calories = 144.0,
            protein = 13.3,
            fat = 8.8,
            carbs = 2.8,
            micronutrients = emptyList(),
            tags = listOf("蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-043",
            name = "鸭蛋",
            calories = 180.0,
            protein = 12.6,
            fat = 13.0,
            carbs = 3.1,
            micronutrients = emptyList(),
            tags = listOf("蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-044",
            name = "鹌鹑蛋",
            calories = 160.0,
            protein = 12.0,
            fat = 11.0,
            carbs = 2.1,
            micronutrients = emptyList(),
            tags = listOf("蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-045",
            name = "牛奶",
            calories = 54.0,
            protein = 3.0,
            fat = 3.2,
            carbs = 4.7,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-046",
            name = "酸奶",
            calories = 72.0,
            protein = 2.5,
            fat = 2.7,
            carbs = 9.3,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-047",
            name = "全脂奶粉",
            calories = 504.0,
            protein = 24.0,
            fat = 27.0,
            carbs = 38.0,
            micronutrients = emptyList(),
            tags = listOf("蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-048",
            name = "豆浆",
            calories = 31.0,
            protein = 3.0,
            fat = 1.6,
            carbs = 1.2,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-049",
            name = "豆腐",
            calories = 76.0,
            protein = 8.0,
            fat = 4.8,
            carbs = 1.9,
            micronutrients = emptyList(),
            tags = listOf("豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-050",
            name = "豆腐干",
            calories = 140.0,
            protein = 16.0,
            fat = 5.0,
            carbs = 8.0,
            micronutrients = emptyList(),
            tags = listOf("豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-051",
            name = "嫩豆腐",
            calories = 48.0,
            protein = 5.2,
            fat = 1.9,
            carbs = 2.0,
            micronutrients = emptyList(),
            tags = listOf("豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-052",
            name = "腐竹",
            calories = 460.0,
            protein = 22.0,
            fat = 21.0,
            carbs = 22.0,
            micronutrients = emptyList(),
            tags = listOf("豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-053",
            name = "千张",
            calories = 260.0,
            protein = 24.0,
            fat = 18.0,
            carbs = 5.0,
            micronutrients = emptyList(),
            tags = listOf("豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-054",
            name = "油豆腐",
            calories = 245.0,
            protein = 17.0,
            fat = 17.0,
            carbs = 5.0,
            micronutrients = emptyList(),
            tags = listOf("调味品", "豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-055",
            name = "豆奶",
            calories = 45.0,
            protein = 3.6,
            fat = 2.0,
            carbs = 2.3,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "豆制品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-056",
            name = "奶酪",
            calories = 328.0,
            protein = 25.0,
            fat = 23.0,
            carbs = 2.4,
            micronutrients = emptyList(),
            tags = listOf("蛋奶"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-057",
            name = "酸奶（无糖）",
            calories = 63.0,
            protein = 3.5,
            fat = 2.0,
            carbs = 8.0,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-058",
            name = "鸡胸肉",
            calories = 133.0,
            protein = 19.4,
            fat = 5.0,
            carbs = 2.7,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-059",
            name = "鸡腿",
            calories = 146.0,
            protein = 20.0,
            fat = 7.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-060",
            name = "鸡翅",
            calories = 202.0,
            protein = 18.0,
            fat = 13.0,
            carbs = 2.7,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-061",
            name = "牛肉（瘦）",
            calories = 106.0,
            protein = 20.2,
            fat = 2.3,
            carbs = 1.2,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-062",
            name = "牛腩",
            calories = 288.0,
            protein = 19.0,
            fat = 20.0,
            carbs = 2.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-063",
            name = "牛排（煎）",
            calories = 250.0,
            protein = 26.0,
            fat = 16.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-064",
            name = "猪肉（瘦）",
            calories = 143.0,
            protein = 20.3,
            fat = 6.2,
            carbs = 1.5,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-065",
            name = "五花肉",
            calories = 549.0,
            protein = 9.0,
            fat = 53.0,
            carbs = 2.4,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-066",
            name = "里脊肉",
            calories = 155.0,
            protein = 21.0,
            fat = 7.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-067",
            name = "排骨",
            calories = 278.0,
            protein = 18.0,
            fat = 23.0,
            carbs = 0.7,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-068",
            name = "羊肉",
            calories = 118.0,
            protein = 20.0,
            fat = 5.0,
            carbs = 1.2,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-069",
            name = "香肠",
            calories = 325.0,
            protein = 14.0,
            fat = 26.0,
            carbs = 11.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-070",
            name = "培根",
            calories = 541.0,
            protein = 37.0,
            fat = 42.0,
            carbs = 1.5,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-071",
            name = "火腿",
            calories = 336.0,
            protein = 16.0,
            fat = 28.0,
            carbs = 2.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-072",
            name = "午餐肉",
            calories = 365.0,
            protein = 13.0,
            fat = 31.0,
            carbs = 4.0,
            micronutrients = emptyList(),
            tags = listOf("肉类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-073",
            name = "鱼丸",
            calories = 97.0,
            protein = 11.0,
            fat = 1.3,
            carbs = 9.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-074",
            name = "虾",
            calories = 85.0,
            protein = 18.0,
            fat = 0.7,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-075",
            name = "虾仁",
            calories = 48.0,
            protein = 10.4,
            fat = 0.7,
            carbs = 0.5,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-076",
            name = "龙虾",
            calories = 90.0,
            protein = 19.0,
            fat = 1.0,
            carbs = 1.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-077",
            name = "螃蟹",
            calories = 103.0,
            protein = 19.0,
            fat = 3.0,
            carbs = 1.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-078",
            name = "三文鱼",
            calories = 208.0,
            protein = 20.4,
            fat = 13.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-079",
            name = "金枪鱼",
            calories = 132.0,
            protein = 28.0,
            fat = 1.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-080",
            name = "鳕鱼",
            calories = 82.0,
            protein = 17.5,
            fat = 0.7,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-081",
            name = "带鱼",
            calories = 127.0,
            protein = 17.7,
            fat = 4.9,
            carbs = 3.1,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-082",
            name = "黄花鱼",
            calories = 97.0,
            protein = 17.7,
            fat = 2.5,
            carbs = 0.3,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-083",
            name = "鲫鱼",
            calories = 108.0,
            protein = 17.4,
            fat = 2.7,
            carbs = 3.9,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-084",
            name = "鲤鱼",
            calories = 109.0,
            protein = 17.6,
            fat = 3.1,
            carbs = 1.8,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-085",
            name = "草鱼",
            calories = 113.0,
            protein = 16.6,
            fat = 5.2,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-086",
            name = "泥鳅",
            calories = 96.0,
            protein = 17.9,
            fat = 2.0,
            carbs = 1.6,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-087",
            name = "鳝鱼",
            calories = 89.0,
            protein = 18.0,
            fat = 1.4,
            carbs = 1.2,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-088",
            name = "鱿鱼",
            calories = 92.0,
            protein = 15.6,
            fat = 1.3,
            carbs = 3.2,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-089",
            name = "墨鱼",
            calories = 83.0,
            protein = 15.0,
            fat = 1.4,
            carbs = 2.5,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-090",
            name = "海参",
            calories = 71.0,
            protein = 13.2,
            fat = 0.9,
            carbs = 1.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-091",
            name = "鲍鱼",
            calories = 85.0,
            protein = 14.8,
            fat = 1.5,
            carbs = 3.5,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-092",
            name = "牡蛎",
            calories = 68.0,
            protein = 7.1,
            fat = 2.1,
            carbs = 5.2,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-093",
            name = "扇贝",
            calories = 111.0,
            protein = 20.0,
            fat = 0.6,
            carbs = 5.0,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-094",
            name = "蛤蜊",
            calories = 62.0,
            protein = 10.0,
            fat = 1.4,
            carbs = 4.1,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-095",
            name = "花蛤",
            calories = 45.0,
            protein = 7.0,
            fat = 0.6,
            carbs = 3.3,
            micronutrients = emptyList(),
            tags = listOf("海鲜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-096",
            name = "西兰花",
            calories = 34.0,
            protein = 2.8,
            fat = 0.4,
            carbs = 7.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-097",
            name = "胡萝卜",
            calories = 41.0,
            protein = 0.9,
            fat = 0.2,
            carbs = 9.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-098",
            name = "番茄",
            calories = 18.0,
            protein = 0.9,
            fat = 0.2,
            carbs = 3.9,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-099",
            name = "黄瓜",
            calories = 15.0,
            protein = 0.7,
            fat = 0.1,
            carbs = 3.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-100",
            name = "白菜",
            calories = 15.0,
            protein = 1.5,
            fat = 0.1,
            carbs = 3.2,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-101",
            name = "菠菜",
            calories = 23.0,
            protein = 2.9,
            fat = 0.4,
            carbs = 3.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-102",
            name = "生菜",
            calories = 15.0,
            protein = 1.4,
            fat = 0.2,
            carbs = 2.9,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-103",
            name = "油菜",
            calories = 14.0,
            protein = 1.3,
            fat = 0.5,
            carbs = 1.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-104",
            name = "芹菜",
            calories = 14.0,
            protein = 0.8,
            fat = 0.1,
            carbs = 2.7,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-105",
            name = "韭菜",
            calories = 26.0,
            protein = 2.4,
            fat = 0.4,
            carbs = 4.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-106",
            name = "蒜苗",
            calories = 37.0,
            protein = 2.1,
            fat = 0.4,
            carbs = 7.4,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-107",
            name = "洋葱",
            calories = 40.0,
            protein = 1.1,
            fat = 0.1,
            carbs = 9.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-108",
            name = "茄子",
            calories = 24.0,
            protein = 1.0,
            fat = 0.2,
            carbs = 5.9,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-109",
            name = "青椒",
            calories = 20.0,
            protein = 0.9,
            fat = 0.2,
            carbs = 4.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-110",
            name = "红椒",
            calories = 31.0,
            protein = 1.0,
            fat = 0.3,
            carbs = 6.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-111",
            name = "辣椒",
            calories = 40.0,
            protein = 1.9,
            fat = 0.2,
            carbs = 8.9,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-112",
            name = "南瓜",
            calories = 26.0,
            protein = 1.0,
            fat = 0.1,
            carbs = 6.5,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-113",
            name = "冬瓜",
            calories = 12.0,
            protein = 0.4,
            fat = 0.2,
            carbs = 2.6,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-114",
            name = "丝瓜",
            calories = 20.0,
            protein = 1.3,
            fat = 0.2,
            carbs = 4.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-115",
            name = "苦瓜",
            calories = 19.0,
            protein = 1.0,
            fat = 0.1,
            carbs = 3.7,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-116",
            name = "豆角",
            calories = 31.0,
            protein = 1.9,
            fat = 0.3,
            carbs = 6.3,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-117",
            name = "四季豆",
            calories = 28.0,
            protein = 1.9,
            fat = 0.1,
            carbs = 5.7,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-118",
            name = "豌豆",
            calories = 81.0,
            protein = 5.4,
            fat = 0.4,
            carbs = 14.5,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-119",
            name = "毛豆",
            calories = 131.0,
            protein = 13.0,
            fat = 5.0,
            carbs = 10.5,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-120",
            name = "黄豆",
            calories = 359.0,
            protein = 35.0,
            fat = 16.0,
            carbs = 34.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-121",
            name = "绿豆",
            calories = 316.0,
            protein = 21.0,
            fat = 0.8,
            carbs = 56.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-122",
            name = "红豆",
            calories = 324.0,
            protein = 20.0,
            fat = 0.6,
            carbs = 55.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-123",
            name = "黑豆",
            calories = 341.0,
            protein = 36.0,
            fat = 15.0,
            carbs = 34.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-124",
            name = "香菇",
            calories = 26.0,
            protein = 2.2,
            fat = 0.1,
            carbs = 4.6,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-125",
            name = "平菇",
            calories = 24.0,
            protein = 1.7,
            fat = 0.3,
            carbs = 4.6,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-126",
            name = "金针菇",
            calories = 32.0,
            protein = 2.9,
            fat = 0.4,
            carbs = 6.0,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-127",
            name = "杏鲍菇",
            calories = 35.0,
            protein = 1.3,
            fat = 0.0,
            carbs = 6.6,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-128",
            name = "木耳",
            calories = 265.0,
            protein = 12.0,
            fat = 1.5,
            carbs = 65.0,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-129",
            name = "银耳",
            calories = 200.0,
            protein = 5.0,
            fat = 1.4,
            carbs = 67.0,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-130",
            name = "海带",
            calories = 13.0,
            protein = 1.2,
            fat = 0.1,
            carbs = 2.1,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-131",
            name = "紫菜",
            calories = 250.0,
            protein = 43.0,
            fat = 1.1,
            carbs = 44.0,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-132",
            name = "蘑菇",
            calories = 22.0,
            protein = 3.1,
            fat = 0.3,
            carbs = 3.3,
            micronutrients = emptyList(),
            tags = listOf("菌菇藻类"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-133",
            name = "苹果",
            calories = 52.0,
            protein = 0.3,
            fat = 0.2,
            carbs = 13.8,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-134",
            name = "香蕉",
            calories = 89.0,
            protein = 1.1,
            fat = 0.3,
            carbs = 22.8,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-135",
            name = "橙子",
            calories = 47.0,
            protein = 0.9,
            fat = 0.1,
            carbs = 11.8,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-136",
            name = "橘子",
            calories = 42.0,
            protein = 0.9,
            fat = 0.1,
            carbs = 10.6,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-137",
            name = "柚子",
            calories = 42.0,
            protein = 0.8,
            fat = 0.2,
            carbs = 9.6,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-138",
            name = "柠檬",
            calories = 29.0,
            protein = 1.1,
            fat = 0.3,
            carbs = 9.3,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-139",
            name = "草莓",
            calories = 32.0,
            protein = 0.7,
            fat = 0.3,
            carbs = 7.7,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-140",
            name = "蓝莓",
            calories = 57.0,
            protein = 0.7,
            fat = 0.3,
            carbs = 14.5,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-141",
            name = "葡萄",
            calories = 62.0,
            protein = 0.6,
            fat = 0.2,
            carbs = 17.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-142",
            name = "提子",
            calories = 67.0,
            protein = 0.6,
            fat = 0.2,
            carbs = 17.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-143",
            name = "西瓜",
            calories = 30.0,
            protein = 0.5,
            fat = 0.1,
            carbs = 8.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-144",
            name = "哈密瓜",
            calories = 34.0,
            protein = 0.8,
            fat = 0.2,
            carbs = 8.2,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-145",
            name = "甜瓜",
            calories = 28.0,
            protein = 0.6,
            fat = 0.1,
            carbs = 6.6,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-146",
            name = "芒果",
            calories = 60.0,
            protein = 0.8,
            fat = 0.4,
            carbs = 15.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-147",
            name = "菠萝",
            calories = 50.0,
            protein = 0.5,
            fat = 0.1,
            carbs = 13.1,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-148",
            name = "猕猴桃",
            calories = 61.0,
            protein = 1.1,
            fat = 0.5,
            carbs = 14.5,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-149",
            name = "火龙果",
            calories = 50.0,
            protein = 0.9,
            fat = 0.2,
            carbs = 11.6,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-150",
            name = "百香果",
            calories = 97.0,
            protein = 2.2,
            fat = 0.7,
            carbs = 23.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-151",
            name = "荔枝",
            calories = 66.0,
            protein = 0.8,
            fat = 0.2,
            carbs = 16.5,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-152",
            name = "龙眼",
            calories = 60.0,
            protein = 1.1,
            fat = 0.1,
            carbs = 15.2,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-153",
            name = "榴莲",
            calories = 147.0,
            protein = 1.5,
            fat = 5.3,
            carbs = 27.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-154",
            name = "山竹",
            calories = 72.0,
            protein = 0.5,
            fat = 0.6,
            carbs = 18.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-155",
            name = "樱桃",
            calories = 50.0,
            protein = 1.1,
            fat = 0.2,
            carbs = 12.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-156",
            name = "桃子",
            calories = 39.0,
            protein = 0.9,
            fat = 0.1,
            carbs = 10.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-157",
            name = "梨",
            calories = 50.0,
            protein = 0.3,
            fat = 0.1,
            carbs = 13.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-158",
            name = "柿子",
            calories = 71.0,
            protein = 0.4,
            fat = 0.1,
            carbs = 18.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-159",
            name = "枣",
            calories = 79.0,
            protein = 1.1,
            fat = 0.2,
            carbs = 20.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-160",
            name = "牛油果",
            calories = 160.0,
            protein = 2.0,
            fat = 14.7,
            carbs = 8.5,
            micronutrients = emptyList(),
            tags = listOf("水果", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-161",
            name = "椰子肉",
            calories = 354.0,
            protein = 3.3,
            fat = 33.5,
            carbs = 15.0,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-162",
            name = "石榴",
            calories = 83.0,
            protein = 1.7,
            fat = 0.6,
            carbs = 18.7,
            micronutrients = emptyList(),
            tags = listOf("水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-163",
            name = "核桃",
            calories = 646.0,
            protein = 15.0,
            fat = 58.0,
            carbs = 14.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-164",
            name = "杏仁",
            calories = 575.0,
            protein = 21.0,
            fat = 50.0,
            carbs = 22.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-165",
            name = "腰果",
            calories = 553.0,
            protein = 18.0,
            fat = 44.0,
            carbs = 30.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-166",
            name = "花生",
            calories = 567.0,
            protein = 24.0,
            fat = 49.0,
            carbs = 16.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-167",
            name = "瓜子",
            calories = 570.0,
            protein = 24.0,
            fat = 50.0,
            carbs = 20.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-168",
            name = "开心果",
            calories = 562.0,
            protein = 20.0,
            fat = 45.0,
            carbs = 28.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-169",
            name = "榛子",
            calories = 628.0,
            protein = 14.0,
            fat = 61.0,
            carbs = 17.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-170",
            name = "松子",
            calories = 670.0,
            protein = 13.0,
            fat = 68.0,
            carbs = 13.0,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-171",
            name = "葡萄干",
            calories = 299.0,
            protein = 3.4,
            fat = 0.5,
            carbs = 79.0,
            micronutrients = emptyList(),
            tags = listOf("坚果", "水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-172",
            name = "红枣",
            calories = 276.0,
            protein = 3.2,
            fat = 0.9,
            carbs = 67.0,
            micronutrients = emptyList(),
            tags = listOf("坚果", "水果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-173",
            name = "桂圆",
            calories = 71.0,
            protein = 1.2,
            fat = 0.2,
            carbs = 16.6,
            micronutrients = emptyList(),
            tags = listOf("坚果"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-174",
            name = "薯片",
            calories = 536.0,
            protein = 7.0,
            fat = 35.0,
            carbs = 53.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-175",
            name = "爆米花",
            calories = 387.0,
            protein = 12.0,
            fat = 4.5,
            carbs = 77.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-176",
            name = "巧克力",
            calories = 546.0,
            protein = 4.9,
            fat = 31.0,
            carbs = 61.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-177",
            name = "糖果",
            calories = 389.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 99.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-178",
            name = "果冻",
            calories = 62.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 15.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-179",
            name = "沙琪玛",
            calories = 444.0,
            protein = 7.0,
            fat = 22.0,
            carbs = 60.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-180",
            name = "甜甜圈",
            calories = 426.0,
            protein = 4.0,
            fat = 22.0,
            carbs = 57.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-181",
            name = "冰淇淋",
            calories = 207.0,
            protein = 3.5,
            fat = 11.0,
            carbs = 28.0,
            micronutrients = emptyList(),
            tags = listOf("零食"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-182",
            name = "奶茶（珍珠）",
            calories = 130.0,
            protein = 1.0,
            fat = 3.2,
            carbs = 25.0,
            micronutrients = emptyList(),
            tags = listOf("蛋奶", "饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-183",
            name = "可乐",
            calories = 42.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 10.6,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-184",
            name = "雪碧",
            calories = 40.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 10.0,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-185",
            name = "橙汁",
            calories = 45.0,
            protein = 0.7,
            fat = 0.2,
            carbs = 10.4,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-186",
            name = "咖啡（黑）",
            calories = 2.0,
            protein = 0.1,
            fat = 0.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-187",
            name = "啤酒",
            calories = 43.0,
            protein = 0.5,
            fat = 0.0,
            carbs = 3.6,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-188",
            name = "红酒",
            calories = 85.0,
            protein = 0.1,
            fat = 0.0,
            carbs = 2.6,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-189",
            name = "白酒",
            calories = 295.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("饮品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-190",
            name = "花生油",
            calories = 899.0,
            protein = 0.0,
            fat = 99.9,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("坚果", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-191",
            name = "橄榄油",
            calories = 884.0,
            protein = 0.0,
            fat = 100.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-192",
            name = "菜籽油",
            calories = 899.0,
            protein = 0.0,
            fat = 99.9,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-193",
            name = "黄油",
            calories = 717.0,
            protein = 0.8,
            fat = 81.0,
            carbs = 0.1,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-194",
            name = "猪油",
            calories = 902.0,
            protein = 0.0,
            fat = 99.6,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-195",
            name = "盐",
            calories = 0.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-196",
            name = "白糖",
            calories = 400.0,
            protein = 0.0,
            fat = 0.0,
            carbs = 100.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-197",
            name = "红糖",
            calories = 389.0,
            protein = 0.4,
            fat = 0.0,
            carbs = 96.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-198",
            name = "蜂蜜",
            calories = 304.0,
            protein = 0.3,
            fat = 0.0,
            carbs = 82.1,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-199",
            name = "酱油",
            calories = 63.0,
            protein = 5.6,
            fat = 0.0,
            carbs = 5.6,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-200",
            name = "醋",
            calories = 31.0,
            protein = 0.3,
            fat = 0.0,
            carbs = 4.5,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-201",
            name = "料酒",
            calories = 66.0,
            protein = 0.2,
            fat = 0.0,
            carbs = 6.5,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-202",
            name = "豆瓣酱",
            calories = 178.0,
            protein = 6.5,
            fat = 4.0,
            carbs = 28.9,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-203",
            name = "辣椒酱",
            calories = 82.0,
            protein = 1.5,
            fat = 3.4,
            carbs = 12.0,
            micronutrients = emptyList(),
            tags = listOf("蔬菜", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-204",
            name = "番茄酱",
            calories = 101.0,
            protein = 1.3,
            fat = 0.2,
            carbs = 24.4,
            micronutrients = emptyList(),
            tags = listOf("蔬菜", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-205",
            name = "沙拉酱",
            calories = 680.0,
            protein = 0.5,
            fat = 74.0,
            carbs = 2.7,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-206",
            name = "芝麻酱",
            calories = 595.0,
            protein = 17.0,
            fat = 54.0,
            carbs = 22.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-207",
            name = "花生酱",
            calories = 598.0,
            protein = 22.0,
            fat = 50.0,
            carbs = 22.0,
            micronutrients = emptyList(),
            tags = listOf("坚果", "调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-208",
            name = "蚝油",
            calories = 107.0,
            protein = 2.8,
            fat = 0.4,
            carbs = 21.3,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
        FoodTemplate(
            id = "preset-food-209",
            name = "味精",
            calories = 358.0,
            protein = 17.0,
            fat = 0.0,
            carbs = 0.0,
            micronutrients = emptyList(),
            tags = listOf("调味品"),
            isPreset = true,
            source = "每100g"
        ),
    )

    /** 获取全部预设模板（id 已固定，便于去重） */
    fun getAll(): List<FoodTemplate> = TEMPLATES
}